### ISSUE TITLE
how to set the default zoom level

### ISSUE THREAD

**Issue by yanwh0311** [Jelmerro/Vieb#473]
how to set the default zoom level

**Comment by Jelmerro** [comment]
Currently there is no setting for this, but it could be added. It does remember the zoom level per domain, but the fixed default is the default zoom of 100%.

**Comment by abvee** [comment]
Any update on this issue ?
Using `--ash-host-window-bounds="1920x1080"` and `--force-scale-factor=1.5` seems to do nothing

**Comment by Jelmerro** [comment]
I have made the interface scaling into a proper supported Vieb flag named `--interface-scale`, hence the force-scale-factor not working, could you try that too? We do definitely still need a proper default zoom, but at least having that flag there should work as a workaround.

**Comment by abvee** [comment]
Trying with `--interface-scale` has some strange results, atleast for me on my tiling window manager.

It might work for someone with a floating window manager ? When I set the `--interface-scale` to 2:
![image](https://github.com/Jelmerro/Vieb/assets/82954751/8f388630-dbdb-4381-9777-38573d13c38b)

It will yell at me that my argument is unsupported if I put `--interface-scale=1.5`, but it does allow for a scale less than 1. that does the opposite of when I set it to 2, and shrinks the entire thing:

![image](https://github.com/Jelmerro/Vieb/assets/82954751/aee41e76-e686-4116-8d15-76ea84e0cfbd)

The problem is that these windows are not floating or anything, they are tiled like that:

![image](https://github.com/Jelmerro/Vieb/assets/82954751/3ed9ec66-b936-425c-9450-0d50b4f73b1a)

**Comment by Jelmerro** [comment]
I think this might be an issue with the window manager indeed. Do you have similar issues with other Electron applications when using the force-scale-factor flag?

**Comment by abvee** [comment]
The only other electron application I have is Discord, and neither `--force-scale-factor` nor `--interface-scale` affect it at all. Discord  does have an option for increasing scaling in settings though. I have no problem with scaling at all in Discord

I should mention I have only tested the `--interface-scale` option on the newest version with the AppImage. Still doesn't work as intended.

**Comment by imiric** [comment]
Hi, are there any updates on this issue? I don't want to have to set the zoom level for each domain, but to set a global default zoom level. I find it surprising that such a basic feature is missing from an otherwise promising browser.

I tried passing `--interface-scale=1.5`, but get the following error:

```
(node:27009) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 1, conversion failure from
    at /opt/Vieb/resources/app.asar/app/index.js:2:4034413
(Use `vieb --trace-warnings ...` to show where the warning was created)
(node:27009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

And the browser doesn't start.

Passing `--trace-warnings` as well shows:

```
(node:27433) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 1, conversion failure from
    at /opt/Vieb/resources/app.asar/app/index.js:2:4034413
    at emitUnhandledRejectionWarning (node:internal/process/promises:201:15)
    at processPromiseRejections (node:internal/process/promises:297:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:27433) TypeError: Error processing argument at index 1, conversion failure from
    at /opt/Vieb/resources/app.asar/app/index.js:2:4034413
```

However, passing `--interface-scale=2` works, so it seems like an issue with float conversion. I don't want to increase the UI scale though, just the site zoom level, so this flag is not the right solution. 

I'm using Vieb 12.0.0 on Void Linux (native amd64, not AppImage).

**Comment by abvee** [comment]
@Jelmerro has been silent for a while (since August). I hope he's alright. So no updates as far as I can see :D

**Comment by Jelmerro** [comment]
No updates so far indeed, back now, so I'll look into the interface scale issue in a few days and hopefully get a new updates out.

**Comment by Jelmerro** [comment]
I fixed the interface scale option at least, turns out it was a silly rounding (or lack thereof) error when setting the minimum window size. It will be fixed in the next release, but still no progress on the default zoom level I must add.
